# Generated by Django 5.1.3 on 2024-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
